HTTP
### Prueba 1: Verificar el estado del Servidor y la Base de Datos
GET http://localhost:3000/api/status

###

### Prueba 2: Registrar un nuevo Operador en la Fábrica
POST http://localhost:3000/api/operadores
Content-Type: application/json

{
  "nombre": "Carlos Mendoza",
  "codigo_empleado": "OP-001",
  "turno": "Tarde"
}

###

### Prueba 3: Registrar una nueva Máquina en la Planta
POST http://localhost:3000/api/maquinas
Content-Type: application/json

{
  "nombre": "Inyectora de Zamak 01",
  "tipo": "Inyección de alta presión"
}

###

### Prueba 4: Registrar un reporte de producción real
POST http://localhost:3000/api/produccion
Content-Type: application/json

{
  "id_operador": 999,
  "id_maquina": 23,
  "cantidad_buena": 150,
  "cantidad_mala": 5
}